GET http://localhost:9034/promotions/1/banners
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzUzOTk2NjYsImlkIjoiSm9obiBTbWl0aCIsIm9yaWdfaWF0IjoxNTM1Mzk2MDY2LCJyb2xlIjowLCJ1c2VybmFtZSI6IkpvaG4gU21pdGgifQ.u0wmQYO4PBxBB4Q-hrHfsE3cZnA-HYEmdP3I9HknAso

###

POST http://localhost:9034/banners
content-type: application/json

< new_banner.json

###


POST http://localhost:9034/banner_places
content-type: application/json

< new_banner_place.json

###

POST http://localhost:8080/signin
Content-Type: application/json

< new_user.json

###

GET http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDk4MjY2ODUsIm9yaWdfaWF0IjoxNTQ5ODIzMDg1LCJyb2xlIjowLCJ1c2VyX2lkIjoxMjEsInVzZXJuYW1lIjoicXFxIn0.ktQOWfyqxxfT0y6AJIu6vjNrOmwTAMmpfbaukzxZjbU

###

DELETE http://localhost:8080/incomes/29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDk4MjY2ODUsIm9yaWdfaWF0IjoxNTQ5ODIzMDg1LCJyb2xlIjowLCJ1c2VyX2lkIjoxMjEsInVzZXJuYW1lIjoicXFxIn0.ktQOWfyqxxfT0y6AJIu6vjNrOmwTAMmpfbaukzxZjbU
Content-Type: application/json

###