GET http://localhost:8080/user HTTP/2.0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzUzOTk2NjYsImlkIjoiSm9obiBTbWl0aCIsIm9yaWdfaWF0IjoxNTM1Mzk2MDY2LCJyb2xlIjowLCJ1c2VybmFtZSI6IkpvaG4gU21pdGgifQ.u0wmQYO4PBxBB4Q-hrHfsE3cZnA-HYEmdP3I9HknAso

###

